In [2]:
import pandas as pd

df = pd.read_csv("../data/raw/amazon_sales.csv")

df.head()

,OrderID,OrderDate,CustomerID,CustomerName,ProductID,ProductName,Category,Brand,Quantity,UnitPrice,Discount,Tax,ShippingCost,TotalAmount,PaymentMethod,OrderStatus,City,State,Country,SellerID
0,ORD0000001,2023-01-31,CUST001504,Vihaan Sharma,P00014,Drone Mini,Books,BrightLux,3,106.59,0.00,0.00,0.09,319.86,Debit Card,Delivered,Washington,DC,India,SELL01967
1,ORD0000002,2023-12-30,CUST000178,Pooja Kumar,P00040,Microphone,Home & Kitchen,UrbanStyle,1,251.37,0.05,19.10,1.74,259.64,Amazon Pay,Delivered,Fort Worth,TX,United States,SELL01298
2,ORD0000003,2022-05-10,CUST047516,Sneha Singh,P00044,Power Bank 20000mAh,Clothing,UrbanStyle,3,35.03,0.10,7.57,5.91,108.06,Debit Card,Delivered,Austin,TX,United States,SELL00908
3,ORD0000004,2023-07-18,CUST030059,Vihaan Reddy,P00041,Webcam Full HD,Home & Kitchen,Zenith,5,33.58,0.15,11.42,5.53,159.66,Cash on Delivery,Delivered,Charlotte,NC,India,SELL01164
4,ORD0000005,2023-02-04,CUST048677,Aditya Kapoor,P00029,T-Shirt,Clothing,KiddoFun,2,515.64,0.25,38.67,9.23,821.36,Credit Card,Cancelled,San Antonio,TX,Canada,SELL01411

In [3]:
print("Rows and Columns:", df.shape)

print("\nColumn Names:")
print(df.columns.tolist())

Rows and Columns: (100000, 20)

Column Names:
['OrderID', 'OrderDate', 'CustomerID', 'CustomerName', 'ProductID', 'ProductName', 'Category', 'Brand', 'Quantity', 'UnitPrice', 'Discount', 'Tax', 'ShippingCost', 'TotalAmount', 'PaymentMethod', 'OrderStatus', 'City', 'State', 'Country', 'SellerID']

In [4]:
# Check data types
print("DATA TYPES:")
print(df.dtypes)

# Check missing values
print("\nMISSING VALUES:")
print(df.isnull().sum())

DATA TYPES:
OrderID           object
OrderDate         object
CustomerID        object
CustomerName      object
ProductID         object
ProductName       object
Category          object
Brand             object
Quantity           int64
UnitPrice        float64
Discount         float64
Tax              float64
ShippingCost     float64
TotalAmount      float64
PaymentMethod     object
OrderStatus       object
City              object
State             object
Country           object
SellerID          object
dtype: object

MISSING VALUES:
OrderID          0
OrderDate        0
CustomerID       0
CustomerName     0
ProductID        0
ProductName      0
Category         0
Brand            0
Quantity         0
UnitPrice        0
Discount         0
Tax              0
ShippingCost     0
TotalAmount      0
PaymentMethod    0
OrderStatus      0
City             0
State            0
Country          0
SellerID         0
dtype: int64

In [5]:
# Check duplicate rows
print("Duplicate Rows:", df.duplicated().sum())

# Basic statistical summary
print("\nSTATISTICAL SUMMARY:")
display(df.describe())

Duplicate Rows: 0

STATISTICAL SUMMARY:

,Quantity,UnitPrice,Discount,Tax,ShippingCost,TotalAmount
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,3.001400,302.905748,0.074226,68.468902,7.406660,918.256479
std,1.413548,171.840797,0.082583,74.131180,4.324057,724.508332
min,1.000000,5.000000,0.000000,0.000000,0.000000,4.270000
25%,2.000000,154.190000,0.000000,15.920000,3.680000,340.890000
50%,3.000000,303.070000,0.050000,45.250000,7.300000,714.315000
75%,4.000000,451.500000,0.100000,96.060000,11.150000,1349.765000
max,5.000000,599.990000,0.300000,538.460000,15.000000,3534.980000

In [6]:
# Check unique values in categorical columns

categorical_columns = df.select_dtypes(include="object").columns

for col in categorical_columns:
    print(f"\n{col}")
    print("Unique values:", df[col].nunique())
    print(df[col].unique()[:10])

OrderID
Unique values: 100000
['ORD0000001' 'ORD0000002' 'ORD0000003' 'ORD0000004' 'ORD0000005'
 'ORD0000006' 'ORD0000007' 'ORD0000008' 'ORD0000009' 'ORD0000010']

OrderDate
Unique values: 1825
['2023-01-31' '2023-12-30' '2022-05-10' '2023-07-18' '2023-02-04'
 '2022-12-31' '2024-09-20' '2022-11-10' '2024-06-26' '2020-05-01']

CustomerID
Unique values: 43233
['CUST001504' 'CUST000178' 'CUST047516' 'CUST030059' 'CUST048677'
 'CUST042705' 'CUST037667' 'CUST031165' 'CUST026965' 'CUST029472']

CustomerName
Unique values: 200
['Vihaan Sharma' 'Pooja Kumar' 'Sneha Singh' 'Vihaan Reddy'
 'Aditya Kapoor' 'Karan Sharma' 'Aarav Verma' 'Rohit Kumar' 'Aman Kapoor'
 'Aarav Reddy']

ProductID
Unique values: 50
['P00014' 'P00040' 'P00044' 'P00041' 'P00029' 'P00023' 'P00030' 'P00028'
 'P00031' 'P00001']

ProductName
Unique values: 50
['Drone Mini' 'Microphone' 'Power Bank 20000mAh' 'Webcam Full HD'
 'T-Shirt' 'Cookware Set' 'Dress Shirt' 'Jeans' 'Kids Toy Car'
 'Wireless Earbuds']

Category
Unique values: 6
['Books' 'Home & Kitchen' 'Clothing' 'Toys & Games' 'Sports & Outdoors'
 'Electronics']

Brand
Unique values: 10
['BrightLux' 'UrbanStyle' 'Zenith' 'KiddoFun' 'ReadMore' 'Apex' 'HomeEase'
 'FitLife' 'CoreTech' 'NexPro']

PaymentMethod
Unique values: 6
['Debit Card' 'Amazon Pay' 'Cash on Delivery' 'Credit Card' 'UPI'
 'Net Banking']

OrderStatus
Unique values: 5
['Delivered' 'Cancelled' 'Pending' 'Shipped' 'Returned']

City
Unique values: 20
['Washington' 'Fort Worth' 'Austin' 'Charlotte' 'San Antonio'
 'Los Angeles' 'Chicago' 'Denver' 'Houston' 'Jacksonville']

State
Unique values: 13
['DC' 'TX' 'NC' 'CA' 'IL' 'CO' 'FL' 'NY' 'WA' 'IN']

Country
Unique values: 5
['India' 'United States' 'Canada' 'Australia' 'United Kingdom']

SellerID
Unique values: 1999
['SELL01967' 'SELL01298' 'SELL00908' 'SELL01164' 'SELL01411' 'SELL01494'
 'SELL01676' 'SELL00510' 'SELL01895' 'SELL01584']

In [7]:
print(df.select_dtypes(include="object").columns.tolist())

['OrderID', 'OrderDate', 'CustomerID', 'CustomerName', 'ProductID', 'ProductName', 'Category', 'Brand', 'PaymentMethod', 'OrderStatus', 'City', 'State', 'Country', 'SellerID']

In [8]:
print("OrderDate Data Type:")
print(df["OrderDate"].dtype)

print("\nFirst 10 Order Dates:")
print(df["OrderDate"].head(10))

OrderDate Data Type:
object

First 10 Order Dates:
0    2023-01-31
1    2023-12-30
2    2022-05-10
3    2023-07-18
4    2023-02-04
5    2022-12-31
6    2024-09-20
7    2022-11-10
8    2024-06-26
9    2020-05-01
Name: OrderDate, dtype: object

In [9]:
# Find numerical columns
numerical_columns = df.select_dtypes(include=["int64", "float64"]).columns

print("Numerical Columns:")
print(numerical_columns.tolist())

print("\nNumerical Data Summary:")
display(df[numerical_columns].describe())

Numerical Columns:
['Quantity', 'UnitPrice', 'Discount', 'Tax', 'ShippingCost', 'TotalAmount']

Numerical Data Summary:

,Quantity,UnitPrice,Discount,Tax,ShippingCost,TotalAmount
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,3.001400,302.905748,0.074226,68.468902,7.406660,918.256479
std,1.413548,171.840797,0.082583,74.131180,4.324057,724.508332
min,1.000000,5.000000,0.000000,0.000000,0.000000,4.270000
25%,2.000000,154.190000,0.000000,15.920000,3.680000,340.890000
50%,3.000000,303.070000,0.050000,45.250000,7.300000,714.315000
75%,4.000000,451.500000,0.100000,96.060000,11.150000,1349.765000
max,5.000000,599.990000,0.300000,538.460000,15.000000,3534.980000

Data Cleaning

In [10]:
df_clean = df.copy()

print("Original Shape:", df.shape)
print("Cleaning Shape:", df_clean.shape)

Original Shape: (100000, 20)
Cleaning Shape: (100000, 20)

In [12]:
#Missing values we will find here

missing = df_clean.isnull().sum()

missing = missing[missing > 0].sort_values(ascending=False)

print("Columns with missing values:")
display(missing)

Columns with missing values:

Series([], dtype: int64)

In [13]:
#now we will find  the duplicate rows for this
duplicates = df_clean.duplicated().sum()
print("Total Duplicated Rows:", duplicates)

Total Duplicated Rows: 0

In [14]:
df_clean.dtypes

OrderID           object
OrderDate         object
CustomerID        object
CustomerName      object
ProductID         object
ProductName       object
Category          object
Brand             object
Quantity           int64
UnitPrice        float64
Discount         float64
Tax              float64
ShippingCost     float64
TotalAmount      float64
PaymentMethod     object
OrderStatus       object
City              object
State             object
Country           object
SellerID          object
dtype: object

In [15]:
# Convert OrderDate into proper datetime format

df_clean["OrderDate"] = pd.to_datetime(df_clean["OrderDate"], errors="coerce")

print("OrderDate Data Type:")
print(df_clean["OrderDate"].dtype)

OrderDate Data Type:
datetime64[ns]

In [16]:
print("Invalid/Missing Dates:", df_clean["OrderDate"].isnull().sum())

Invalid/Missing Dates: 0

In [17]:
text_columns = df_clean.select_dtypes(include="object").columns

for col in text_columns:
    df_clean[col] = df_clean[col].str.strip()

In [18]:
print("Categories:")
print(df_clean["Category"].unique())

print("\nPayment Methods:")
print(df_clean["PaymentMethod"].unique())

print("\nOrder Status:")
print(df_clean["OrderStatus"].unique())

Categories:
['Books' 'Home & Kitchen' 'Clothing' 'Toys & Games' 'Sports & Outdoors'
 'Electronics']

Payment Methods:
['Debit Card' 'Amazon Pay' 'Cash on Delivery' 'Credit Card' 'UPI'
 'Net Banking']

Order Status:
['Delivered' 'Cancelled' 'Pending' 'Shipped' 'Returned']

In [19]:
# Identify numeric columns
numeric_cols = df_clean.select_dtypes(include=["int64", "float64"]).columns

print("Numeric Columns:")
print(numeric_cols.tolist())

print("\nMinimum Values:")
display(df_clean[numeric_cols].min())

print("\nMaximum Values:")
display(df_clean[numeric_cols].max())

Numeric Columns:
['Quantity', 'UnitPrice', 'Discount', 'Tax', 'ShippingCost', 'TotalAmount']

Minimum Values:

Quantity        1.00
UnitPrice       5.00
Discount        0.00
Tax             0.00
ShippingCost    0.00
TotalAmount     4.27
dtype: float64

Maximum Values:

Quantity           5.00
UnitPrice        599.99
Discount           0.30
Tax              538.46
ShippingCost      15.00
TotalAmount     3534.98
dtype: float64

In [21]:
# Check negative values in numeric columns

for col in numeric_cols:
    negative_count = (df_clean[col] < 0).sum()
    print(f"{col}: {negative_count} negative values")

Quantity: 0 negative values
UnitPrice: 0 negative values
Discount: 0 negative values
Tax: 0 negative values
ShippingCost: 0 negative values
TotalAmount: 0 negative values

In [ ]:
print("FINAL DATA QUALITY CHECK")

print("\n1. Dataset Shape:")
print(df_clean.shape)

print("\n2. Missing Values:")
print(df_clean.isnull().sum().sum())

print("\n3. Duplicate Rows:")
print(df_clean.duplicated().sum())

print("\n4. Data Types:")
print(df_clean.dtypes)